### ISSUE TITLE
replit issue

### ISSUE THREAD

**Issue by Kambran** [NovaAppsInc/fracital-static#5]
when i run npm install and npm start i get:

ReferenceError: m is not defined
    at Object.<anonymous> (/home/runner/working-vm-cool/index.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uv-app@1.0.0 start: `node .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uv-app@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
![Screenshot 2022-04-11 10 16 16](https://user-images.githubusercontent.com/78663738/162759190-fb6872bd-af8c-49d0-b13e-008886ff819f.png)

npm ERR!     /home/runner/.npm/_logs/2022-04-11T14_13_08_074Z-debug.log

**Comment by Kambran** [comment]
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Critical      │ Prototype Pollution in minimist                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimist                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.2.6                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ node-static                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ node-static > optimist > minimist                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://github.com/advisories/GHSA-xvch-5gv4-984h            │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype Pollution in minimist                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimist                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.2.1                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ node-static                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ node-static > optimist > minimist                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://github.com/advisories/GHSA-vh95-rmgr-6w4m            │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Denial of Service in node-static                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ node-static                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ node-static                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ node-static                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://github.com/advisories/GHSA-8r4g-cg4m-x23c            │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 3 vulnerabilities (2 moderate, 1 critical) in 9 scanned packages
  3 vulnerabilities require manual review. See the full report for details.
